#!/usr/bin/env sh

CLJS_JAR=https://github.com/clojure/clojurescript/releases/download/r1.9.854/cljs.jar

if [ ! -f "cljs.jar" ]
then
  wget $CLJS_JAR
fi

if [ -f "main.js" ]
then
  echo "Cleaning build artifact."
  rm main.js
fi

if [ -d "out" ]
then
  echo "Cleaning build intermediates."
  rm -r out
fi

echo "Building..."
java -cp cljs.jar:src clojure.main scripts/build.clj
echo "Done!"
