#!/usr/bin/env sh

if [ -f "main.js" ]
then
  echo "Cleaning build artifact."
  rm main.js
fi

if [ -d "out" ]
then
  echo "Cleaning build intermediates."
  rm -r out
fi

echo "Building..."
java -cp cljs.jar:src clojure.main scripts/build.clj
echo "Done!"
